/* Finite authorized browser verification. Keeps profile and all artifacts.
   Run only after the guarded offline suite passes; this file is not discovered by it. */
const fs = require('node:fs');
const path = require('node:path');
const {spawn} = require('node:child_process');
const {randomUUID} = require('node:crypto');
const assert = require('node:assert/strict');
const {chromium} = require('C:/Users/Blair/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root = path.resolve(__dirname, '..');
const artifacts = path.join(root, 'paper_trading/state/test-artifacts', `browser-${randomUUID()}`);
const profile = path.join(artifacts, 'profile'), browserArtifacts = path.join(artifacts, 'browser-artifacts');
for (const dir of [artifacts, profile, browserArtifacts]) fs.mkdirSync(dir, {recursive:true});
console.log(`Preserved browser evidence: ${artifacts}`);
let context, server, output = '', origin;
const results = {mode:'paper', data_origin:'synthetic_ui_fixture', actions:[], errors:[], blocked:[]};
const step = text => { results.actions.push(text); console.log(text); };
async function main() {
  server = spawn(path.join(root, '.venv-paper/Scripts/python.exe'), ['-B','-m','trading_stack.paper_server','--data-root',path.join(root,'tests/fixtures/paper-session'),'--output-root',artifacts,'--port','0'], {cwd:root, windowsHide:true, env:{...process.env, PYTHONDONTWRITEBYTECODE:'1',TEAKA_MODE:'paper'}});
  server.stdout.on('data', data => { output += data.toString(); });
  server.stderr.on('data', data => { output += data.toString(); });
  origin = await new Promise((resolve,reject) => {
    const timer = setTimeout(() => reject(new Error('Launcher timeout')),20000);
    server.stdout.on('data', () => { const match = output.match(/PAPER_URL=(http:\/\/127\.0\.0\.1:\d+)/); if (match) {clearTimeout(timer);resolve(match[1]);} });
    server.on('exit', code => {clearTimeout(timer);reject(new Error(`Launcher exited ${code}`));});
  });
  results.origin = origin;
  context = await chromium.launchPersistentContext(profile, {executablePath:'C:/Users/Blair/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe',artifactsDir:browserArtifacts,headless:true,viewport:{width:1440,height:1080},acceptDownloads:false,serviceWorkers:'block'});
  await context.route('**/*', route => {
    if (new URL(route.request().url()).origin === origin) return route.continue();
    results.blocked.push(route.request().url()); return route.abort();
  });
  await context.routeWebSocket('**/*', socket => socket.close());
  const page = context.pages()[0]; page.on('pageerror', error => results.errors.push(error.message));
  await page.goto(`${origin}/auth/register`);
  const password = randomUUID();
  await page.locator('[name=username]').fill('paper_browser_fixture');
  await page.locator('[name=email]').fill('paper-browser@example.invalid');
  await page.locator('[name=password]').fill(password); await page.locator('[name=confirm_password]').fill(password);
  await page.getByRole('button',{name:'Create session user',exact:true}).click();
  await page.locator('[name=username]').fill('paper_browser_fixture'); await page.locator('[name=password]').fill(password);
  await page.getByRole('button',{name:'Log in locally',exact:true}).click();
  await page.waitForURL('**/dashboard');
  await page.waitForFunction(() => document.querySelector('#cash').textContent.includes('USDT'));
  step('Registered and logged in disposable memory-only user through local forms.');
  await page.locator('#strategy-form [name=exit_threshold]').fill('102');
  await page.getByRole('button',{name:'Save strategy',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#action-status').textContent.includes('Strategy saved'));
  let definitions = await page.evaluate(async () => (await fetch('/api/strategies')).json());
  assert.equal(definitions[0].entry_conditions[0].side,'BUY'); assert.equal(definitions[0].exit_conditions[0].side,'SELL');
  await page.locator('#strategy-form [name=name]').fill('Synthetic SELL-only example');
  await page.locator('#strategy-form [name=side]').selectOption('SELL');
  await page.getByRole('button',{name:'Save strategy',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('#strategies tbody tr').length === 2);
  step('Created BUY strategy with explicit SELL exit and second SELL-only strategy using rendered editor.');
  await page.locator('summary').click();
  await page.screenshot({path:path.join(artifacts,'01-ready-to-replay.png'),fullPage:true});
  await page.getByRole('button',{name:'Run finite replay',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#action-status').textContent.includes('Replay complete'));
  const replay = JSON.parse(await page.locator('#replay-result').innerText());
  assert.ok(replay.fill_count >= 2); assert.equal(replay.candle_count,5); assert.ok(replay.source_sha256);
  results.replay = replay; results.cashAfterReplay = await page.locator('#cash').innerText();
  step('Replayed five synthetic candles through local CSV/range/origin form; inspected actual fills, cash, source hash.');
  await page.getByRole('button',{name:'Submit paper order',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#action-status').textContent.includes('Paper order filled'));
  assert.equal(JSON.parse(await page.locator('#manual-result').innerText()).data.status,'filled');
  await page.getByRole('button',{name:'Close paper position',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#action-status').textContent.includes('position closed'));
  assert.ok((await page.locator('#positions').innerText()).includes('No records'));
  results.manualClose = JSON.parse(await page.locator('#manual-result').innerText());
  step('Submitted 0.1-unit paper BUY and closed the owned position through rendered controls.');
  await page.screenshot({path:path.join(artifacts,'02-replay-and-manual-close.png'),fullPage:true});
  await page.getByRole('link',{name:'Candles',exact:true}).click();
  await page.getByRole('button',{name:'Show candles',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('#candles tbody tr').length === 5);
  step('Inspected five completed candles on local market-data page.');
  await page.getByRole('link',{name:'Signals & fills',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('#trades tbody tr').length >= 4);
  step('Verified real signal and execution tables on the signals page.');
  await page.getByRole('link',{name:'Backtesting',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('#backtest-strategy option').length === 2);
  await page.getByRole('button',{name:'Run dated backtest',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#action-status').textContent.includes('Dated backtest complete'));
  results.backtest = JSON.parse(await page.locator('#backtest-result').innerText());
  assert.equal(results.backtest.trading_pair,'BTC/USDT'); assert.ok(results.backtest.total_trades > 0);
  await page.screenshot({path:path.join(artifacts,'03-dated-backtest.png'),fullPage:true});
  step('Executed dated owned-strategy backtest with actual local results and history.');
  await page.getByRole('link',{name:'Settings',exact:true}).click();
  await page.locator('[name=max_position_size_pct]').fill('6');
  await page.getByRole('button',{name:'Save paper risk settings',exact:true}).click();
  assert.ok((await page.locator('body').innerText()).includes('Paper risk settings saved'));
  await page.screenshot({path:path.join(artifacts,'04-settings.png'),fullPage:true});
  await page.getByRole('link',{name:'Profile',exact:true}).click();
  assert.ok((await page.locator('body').innerText()).includes('Profile and password changes are unavailable'));
  step('Saved paper risk settings; verified truthful disabled account/notification/profile controls.');
  // A blocked own-origin API request must visibly mark any retained values stale.
  await page.getByRole('link',{name:'Session',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#cash').textContent.includes('USDT'));
  await page.route('**/api/paper/status', route => route.abort());
  await page.getByRole('button',{name:'Refresh session',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('#data-state').textContent.includes('may be stale'));
  step('Forced API refresh failure and verified visible stale/unavailable warning.');
  assert.deepEqual(results.errors,[]);
  results.success = true;
}
main().catch(error => { results.failure = error.stack; process.exitCode = 1; console.error(error.message); }).finally(async () => {
  if (context) await context.close();
  if (server && server.exitCode === null) { server.kill(); await new Promise(resolve => server.once('exit',resolve)); }
  fs.writeFileSync(path.join(artifacts,'launcher-output.txt'),output);
  fs.writeFileSync(path.join(artifacts,'browser-results.json'),JSON.stringify(results,null,2));
  console.log(results.success ? 'Browser smoke PASS; owned processes stopped; artifacts retained.' : 'Browser smoke FAILED; owned processes stopped; artifacts retained.');
});
